// Server-side only (not served to the client) so the answer key can't be inspected in the browser.
// Curated common-English word lists used to validate whether a submitted answer is a real word,
// not just a random string that happens to start with the right letter.
// Some words legitimately appear in more than one category (e.g. "kiwi" is an animal, a plant and a food).

const NAME = [
  'aaron', 'abdullah', 'abel', 'abigail', 'ada', 'adam', 'adele', 'adnan', 'adrian', 'adriana', 'ahmed', 'aiden', 'aisha', 'akira', 'alan', 'albert', 'alberto', 'alejandro', 'alessandro', 'alex', 'alexander', 'alexandra', 'alfred', 'ali', 'alice', 'alicia', 'alina', 'allison', 'alma', 'alvin', 'amanda', 'amber', 'amelia', 'amina', 'amir', 'amy', 'anastasia', 'andre', 'andrea', 'andres', 'andrew', 'angel', 'angela', 'angelina', 'anita', 'anna', 'anne', 'anthony', 'anton', 'antonia', 'antonio', 'april', 'arda', 'ariana', 'ariel', 'arnold', 'arthur', 'arturo', 'asli', 'astrid', 'athena', 'audrey', 'august', 'aurora', 'austin', 'ava', 'axel', 'ayesha', 'ayla', 'aylin',
  'bailey', 'barbara', 'barry', 'bartholomew', 'basil', 'beatrice', 'beatriz', 'becky', 'bella', 'ben', 'benjamin', 'bernard', 'bertha', 'beth', 'betty', 'bianca', 'bilal', 'bill', 'billy', 'bjorn', 'blake', 'bob', 'bobby', 'boris', 'brad', 'bradley', 'brandon', 'brenda', 'brett', 'brian', 'bridget', 'brittany', 'brooke', 'bruce', 'bruno', 'bryan', 'burak',
  'caitlin', 'caleb', 'calvin', 'camila', 'candice', 'cara', 'carl', 'carla', 'carlo', 'carlos', 'carmen', 'carol', 'caroline', 'carter', 'casey', 'cassandra', 'catherine', 'cecilia', 'cesar', 'chad', 'chandler', 'charlie', 'charlotte', 'chelsea', 'chloe', 'chris', 'christian', 'christina', 'christopher', 'cindy', 'claire', 'clara', 'clarence', 'clark', 'claudia', 'clayton', 'clifford', 'clint', 'cole', 'colin', 'connor', 'constance', 'cora', 'corey', 'courtney', 'craig', 'cristiano', 'crystal', 'curtis', 'cynthia',
  'daisy', 'dakota', 'dale', 'dalia', 'damian', 'damon', 'dan', 'dana', 'daniel', 'danielle', 'danny', 'dante', 'daphne', 'darius', 'darlene', 'darren', 'dave', 'david', 'dawn', 'dean', 'deborah', 'denise', 'deniz', 'dennis', 'derek', 'desmond', 'dexter', 'diana', 'dianne', 'diego', 'dimitri', 'dino', 'dolores', 'dominic', 'dominik', 'don', 'donald', 'donna', 'dora', 'doris', 'dorothy', 'douglas', 'drake', 'duane', 'dustin', 'dylan',
  'earl', 'ebru', 'ece', 'eddie', 'edgar', 'edith', 'edward', 'edwin', 'efe', 'eleanor', 'elena', 'eli', 'elias', 'elif', 'elijah', 'elisa', 'elise', 'elizabeth', 'ella', 'ellen', 'elliot', 'elliott', 'elmer', 'elsa', 'elton', 'elvira', 'emil', 'emilio', 'emily', 'emine', 'emir', 'emma', 'emmanuel', 'emrah', 'emre', 'enrique', 'eric', 'erica', 'erik', 'erin', 'ernest', 'ernesto', 'esma', 'esra', 'esther', 'ethan', 'eugene', 'eva', 'evan', 'eve', 'evelyn',
  'fabian', 'faith', 'farah', 'farid', 'fatima', 'fatma', 'faye', 'felicity', 'felipe', 'felix', 'fernando', 'fidel', 'filiz', 'fiona', 'fletcher', 'flora', 'florence', 'floyd', 'francesca', 'francis', 'francisco', 'frank', 'fred', 'freddie', 'frederick', 'freya', 'fritz', 'furkan',
  'gabriel', 'gabriela', 'gail', 'galina', 'gareth', 'garrett', 'gary', 'gavin', 'gemma', 'genevieve', 'geoffrey', 'george', 'gerald', 'gerardo', 'gianna', 'gilbert', 'gina', 'gino', 'giovanni', 'giselle', 'gloria', 'gonzalo', 'gordon', 'grace', 'graham', 'grant', 'greg', 'gregory', 'greta', 'gretchen', 'guillermo', 'gustavo', 'gwen',
  'habib', 'hailey', 'hakan', 'hale', 'halil', 'hamid', 'hamza', 'hana', 'hannah', 'hans', 'harold', 'harper', 'harriet', 'harry', 'harvey', 'hasan', 'hassan', 'hayley', 'hazel', 'heather', 'hector', 'heidi', 'helen', 'henri', 'henry', 'herbert', 'hilary', 'hilda', 'hiro', 'holly', 'hope', 'horace', 'howard', 'hugo', 'hussein',
  'ian', 'ibrahim', 'ida', 'igor', 'ilya', 'iman', 'imani', 'imogen', 'ines', 'ingrid', 'irem', 'irene', 'irfan', 'irina', 'iris', 'irving', 'isaac', 'isabel', 'isabella', 'isaiah', 'isla', 'ismail', 'ivan', 'ivo', 'ivy',
  'jack', 'jacob', 'jacqueline', 'jade', 'jamal', 'james', 'jamie', 'jane', 'janet', 'janice', 'jared', 'jasmine', 'jason', 'jasper', 'javier', 'jayden', 'jean', 'jeff', 'jeffrey', 'jenna', 'jennifer', 'jenny', 'jeremiah', 'jeremy', 'jerome', 'jerry', 'jesse', 'jessica', 'jessie', 'jill', 'jim', 'jimmy', 'joan', 'joanna', 'jocelyn', 'jody', 'joe', 'joel', 'joey', 'johan', 'johanna', 'john', 'jon', 'jonas', 'jonathan', 'jordan', 'jose', 'joseph', 'joshua', 'josie', 'joy', 'joyce', 'juan', 'judith', 'judy', 'jules', 'julia', 'julian', 'julio', 'june', 'justin', 'justine',
  'kaan', 'kadir', 'kai', 'kamal', 'kara', 'karen', 'karim', 'karl', 'karla', 'katarina', 'kate', 'katherine', 'kathleen', 'kathryn', 'katie', 'katrina', 'kayla', 'keanu', 'keith', 'kelly', 'kemal', 'kendall', 'kendra', 'kenji', 'kenneth', 'kenny', 'kerem', 'kerry', 'kevin', 'khalid', 'kian', 'kim', 'kimberly', 'kira', 'kirsten', 'klaus', 'kobe', 'kris', 'krista', 'kristen', 'kristina', 'kurt', 'kyle',
  'lacey', 'lamar', 'lance', 'lara', 'larry', 'lars', 'latifa', 'laura', 'laurel', 'lauren', 'laurie', 'lawrence', 'layla', 'leah', 'lee', 'leia', 'leila', 'lena', 'lenny', 'leo', 'leon', 'leona', 'leonard', 'leonardo', 'leslie', 'leyla', 'liam', 'lidia', 'lila', 'lillian', 'lily', 'lincoln', 'linda', 'lindsay', 'lionel', 'lisa', 'lloyd', 'logan', 'lola', 'lorena', 'lorenzo', 'lori', 'lorraine', 'louis', 'louise', 'lucas', 'lucia', 'luciano', 'lucy', 'ludwig', 'luis', 'luisa', 'lukas', 'luke', 'luna', 'luther', 'lydia',
  'mabel', 'mack', 'madison', 'magda', 'magnus', 'mahir', 'mahmoud', 'malcolm', 'malik', 'manuel', 'manuela', 'marcel', 'marcelo', 'marcia', 'marco', 'marcus', 'margaret', 'marge', 'marguerite', 'maria', 'mariam', 'marie', 'marina', 'mario', 'marisol', 'marissa', 'mark', 'marlene', 'marlon', 'marsha', 'marta', 'martha', 'martin', 'martina', 'marty', 'marvin', 'mary', 'mason', 'mateo', 'matias', 'matteo', 'matthew', 'maurice', 'mauricio', 'mavis', 'max', 'maximilian', 'maxwell', 'may', 'maya', 'megan', 'mehmet', 'melih', 'melinda', 'melissa', 'melody', 'melvin', 'mercedes', 'meredith', 'merve', 'meryem', 'mia', 'michael', 'mick', 'mickey', 'miguel', 'mike', 'mila', 'milena', 'miles', 'milo', 'mina', 'minnie', 'miranda', 'miriam', 'mitchell', 'mohammed', 'moira', 'molly', 'mona', 'monica', 'morgan', 'morris', 'mostafa', 'muhammad', 'murat', 'mustafa', 'myra', 'myron',
  'nadia', 'nadir', 'nancy', 'naomi', 'nasser', 'natalie', 'natasha', 'nathan', 'nathaniel', 'nazli', 'ned', 'neil', 'nellie', 'nelly', 'nelson', 'nero', 'nestor', 'nicholas', 'nick', 'nicky', 'nicolas', 'nicole', 'niels', 'nigel', 'nikita', 'nikola', 'nikolai', 'nils', 'nina', 'noah', 'noel', 'noelle', 'nolan', 'nora', 'norma', 'norman', 'nour', 'nuray', 'nuri',
  'octavia', 'odette', 'ofelia', 'oksana', 'olaf', 'oleg', 'olga', 'oliver', 'olivia', 'olivier', 'omar', 'omer', 'onur', 'ophelia', 'orhan', 'orlando', 'orson', 'oscar', 'osman', 'oswald', 'otis', 'otto', 'owen', 'ozan',
  'pablo', 'paco', 'paloma', 'pam', 'pamela', 'paolo', 'pascal', 'pat', 'patricia', 'patrick', 'patsy', 'patti', 'paul', 'paula', 'pauline', 'pearl', 'pedro', 'peggy', 'pelin', 'penelope', 'penny', 'percy', 'perry', 'peter', 'petra', 'phil', 'philip', 'phillip', 'phoebe', 'phoenix', 'pierre', 'pilar', 'piper', 'polly', 'preston', 'priscilla', 'priya',
  'qasim', 'queenie', 'quentin', 'quincy', 'quinn', 'quinton',
  'rachel', 'rafael', 'ralph', 'ramon', 'ramona', 'randall', 'randy', 'raquel', 'rashid', 'raul', 'ray', 'raymond', 'rebecca', 'reggie', 'regina', 'remy', 'renata', 'renato', 'rene', 'renee', 'rex', 'rhonda', 'ricardo', 'richard', 'ricky', 'riley', 'rita', 'rob', 'robbie', 'robert', 'roberto', 'robin', 'rocco', 'rodney', 'rodrigo', 'roger', 'roland', 'rolando', 'roman', 'romeo', 'ron', 'ronald', 'ronnie', 'rory', 'rosa', 'rosalie', 'rosario', 'roscoe', 'rose', 'rosie', 'ross', 'roxanne', 'roy', 'ruben', 'ruby', 'rudolf', 'rudy', 'rufus', 'rupert', 'russ', 'russell', 'rusty', 'ruth', 'ryan', 'ryder',
  'sabri', 'sadie', 'said', 'salim', 'sally', 'salma', 'salvador', 'salvatore', 'sam', 'samantha', 'samir', 'sammy', 'samuel', 'sandra', 'sandro', 'sanjay', 'santiago', 'sara', 'sarah', 'sasha', 'saul', 'savannah', 'scarlett', 'scott', 'seamus', 'sean', 'sebastian', 'selena', 'selim', 'selin', 'serdar', 'serena', 'serge', 'sergei', 'sergio', 'seth', 'seymour', 'shakira', 'shane', 'shannon', 'sharon', 'shawn', 'sheila', 'shelby', 'sheldon', 'shelly', 'sherman', 'sherry', 'shirley', 'sid', 'sidney', 'sierra', 'silas', 'silvia', 'simon', 'simone', 'sinan', 'skylar', 'sofia', 'sonia', 'sonny', 'sophia', 'sophie', 'soren', 'spencer', 'stacy', 'stan', 'stanley', 'stefan', 'stella', 'stephanie', 'stephen', 'steven', 'stewart', 'stuart', 'sue', 'suleyman', 'summer', 'susan', 'susanna', 'suzanne', 'sven', 'sybil', 'sylvia',
  'tahir', 'talia', 'tamara', 'tanner', 'tanya', 'tara', 'tariq', 'tatiana', 'taylor', 'ted', 'teddy', 'terence', 'teresa', 'terry', 'tess', 'thea', 'thelma', 'theo', 'theodore', 'theresa', 'thomas', 'tim', 'timothy', 'timur', 'tina', 'tito', 'tobias', 'todd', 'tolga', 'tom', 'tomas', 'tommy', 'toni', 'tony', 'tonya', 'tracy', 'travis', 'trent', 'trevor', 'tricia', 'tristan', 'troy', 'trudy', 'tugba', 'turgut', 'tyler', 'tyrone',
  'ugur', 'ulises', 'ulrich', 'uma', 'umut', 'uriel', 'ursula',
  'vadim', 'val', 'valentin', 'valentina', 'valeria', 'valerie', 'vance', 'vanessa', 'vera', 'vern', 'vernon', 'veronica', 'vicente', 'vicky', 'victor', 'victoria', 'vida', 'viktor', 'vince', 'vincent', 'vinnie', 'viola', 'violet', 'virgil', 'virginia', 'vito', 'vivian', 'vlad', 'vladimir',
  'wade', 'waldo', 'wallace', 'walt', 'walter', 'wanda', 'ward', 'warren', 'wayne', 'wendell', 'wendy', 'wesley', 'whitney', 'wilbur', 'wilfred', 'wilhelm', 'william', 'willow', 'wilma', 'wilson', 'winifred', 'winnie', 'winston', 'wyatt',
  'xander', 'xavier', 'xena', 'ximena', 'xiomara',
  'yakup', 'yara', 'yasin', 'yasmin', 'yavuz', 'yolanda', 'yousef', 'yunus', 'yuri', 'yusuf', 'yvette', 'yvonne',
  'zachary', 'zack', 'zackary', 'zahra', 'zara', 'zeke', 'zelda', 'zeynep', 'ziad', 'ziya', 'zoe', 'zoey', 'zoltan', 'zoya',
];

const CITY = [
  'aarhus', 'aberdeen', 'abidjan', 'abu dhabi', 'abuja', 'acapulco', 'accra', 'adana', 'addis ababa', 'adelaide', 'agra', 'ahmedabad', 'albany', 'albuquerque', 'aleppo', 'alexandria', 'algiers', 'alicante', 'almaty', 'amman', 'amritsar', 'amsterdam', 'anchorage', 'ankara', 'antalya', 'antwerp', 'arequipa', 'arlington', 'asmara', 'astana', 'asuncion', 'athens', 'atlanta', 'auckland', 'austin', 'avignon',
  'baghdad', 'baku', 'bali', 'baltimore', 'bandung', 'bangalore', 'bangkok', 'bangui', 'banjul', 'barcelona', 'barranquilla', 'basel', 'basra', 'bath', 'baton rouge', 'beijing', 'beirut', 'belem', 'belfast', 'belgrade', 'benghazi', 'bergen', 'berlin', 'bern', 'bhopal', 'bilbao', 'birmingham', 'bissau', 'blackpool', 'bogota', 'boise', 'bologna', 'bonn', 'bordeaux', 'boston', 'braga', 'brasilia', 'bratislava', 'bremen', 'brisbane', 'bristol', 'brno', 'bruges', 'brussels', 'bucharest', 'budapest', 'buenos aires', 'buffalo', 'bursa', 'busan',
  'cadiz', 'cagliari', 'cairo', 'calgary', 'cali', 'cambridge', 'canberra', 'cancun', 'cannes', 'cape town', 'caracas', 'cardiff', 'cartagena', 'casablanca', 'catania', 'cebu', 'changsha', 'charleston', 'charlotte', 'chengdu', 'chennai', 'chester', 'chiang mai', 'chicago', 'chisinau', 'chittagong', 'christchurch', 'cincinnati', 'cleveland', 'coimbra', 'cologne', 'colombo', 'columbus', 'conakry', 'copenhagen', 'cordoba', 'cork', 'coventry', 'curitiba', 'cusco',
  'dakar', 'dalian', 'dallas', 'damascus', 'dar es salaam', 'darwin', 'davao', 'delhi', 'denver', 'detroit', 'dhaka', 'dijon', 'doha', 'dortmund', 'douala', 'dresden', 'dubai', 'dublin', 'dubrovnik', 'dundee', 'dunedin', 'durban', 'durham', 'dushanbe', 'dusseldorf',
  'edinburgh', 'edmonton', 'eindhoven', 'el paso', 'erbil', 'erzurum', 'eskisehir', 'essen', 'exeter',
  'faisalabad', 'fargo', 'fes', 'florence', 'fortaleza', 'frankfurt', 'fresno', 'fukuoka',
  'gaborone', 'galway', 'gaza', 'gaziantep', 'gdansk', 'geneva', 'genoa', 'ghent', 'giza', 'glasgow', 'gothenburg', 'granada', 'graz', 'grenoble', 'guadalajara', 'guangzhou', 'guatemala city', 'guayaquil',
  'haifa', 'halifax', 'hamburg', 'hamilton', 'hangzhou', 'hanoi', 'hannover', 'harare', 'harbin', 'hartford', 'havana', 'heidelberg', 'helsinki', 'hiroshima', 'hobart', 'hong kong', 'honolulu', 'houston', 'hull', 'hyderabad',
  'ibadan', 'incheon', 'indianapolis', 'innsbruck', 'irkutsk', 'isfahan', 'islamabad', 'istanbul', 'izmir',
  'jackson', 'jacksonville', 'jaipur', 'jakarta', 'jeddah', 'jerusalem', 'johannesburg', 'juba',
  'kabul', 'kampala', 'kandahar', 'kano', 'kanpur', 'kansas city', 'kaohsiung', 'karachi', 'kathmandu', 'kaunas', 'kazan', 'kharkiv', 'khartoum', 'kiev', 'kigali', 'kingston', 'kinshasa', 'kobe', 'kolkata', 'konya', 'krakow', 'kuala lumpur', 'kuwait city', 'kyoto',
  'la paz', 'lagos', 'lahore', 'las vegas', 'lausanne', 'leeds', 'leicester', 'leipzig', 'leon', 'lexington', 'libreville', 'liege', 'lille', 'lilongwe', 'lima', 'linz', 'lisbon', 'liverpool', 'ljubljana', 'lodz', 'lome', 'london', 'los angeles', 'louisville', 'luanda', 'lucerne', 'lucknow', 'lusaka', 'luxembourg', 'lviv', 'lyon',
  'macau', 'madison', 'madrid', 'malaga', 'male', 'malmo', 'managua', 'manaus', 'manchester', 'manila', 'mannheim', 'maputo', 'maracaibo', 'marrakesh', 'marseille', 'mashhad', 'mecca', 'medan', 'medellin', 'medina', 'melbourne', 'memphis', 'mendoza', 'merida', 'mersin', 'messina', 'mexico city', 'miami', 'milan', 'milwaukee', 'minneapolis', 'minsk', 'mogadishu', 'mombasa', 'monaco', 'monrovia', 'monterrey', 'montevideo', 'montpellier', 'montreal', 'moscow', 'mosul', 'multan', 'mumbai', 'munich', 'muscat', 'mysore',
  'nagoya', 'nagpur', 'nairobi', 'nanjing', 'nantes', 'naples', 'nashville', 'nassau', 'new york', 'newark', 'newcastle', 'niamey', 'nice', 'nicosia', 'ningbo', 'norfolk', 'nottingham', 'nouakchott', 'novosibirsk', 'nuremberg',
  'oaxaca', 'odense', 'odessa', 'oklahoma city', 'omaha', 'omsk', 'oran', 'orlando', 'orleans', 'osaka', 'oslo', 'ostrava', 'ottawa', 'oviedo', 'oxford',
  'padua', 'palembang', 'palermo', 'palma', 'pamplona', 'panama city', 'paramaribo', 'paris', 'parma', 'pasadena', 'patna', 'pattaya', 'perth', 'peshawar', 'philadelphia', 'phoenix', 'pisa', 'pittsburgh', 'plovdiv', 'plymouth', 'podgorica', 'port moresby', 'portland', 'porto', 'porto alegre', 'portsmouth', 'poznan', 'prague', 'pretoria', 'pristina', 'providence', 'puebla', 'pune', 'pyongyang',
  'qingdao', 'qom', 'quebec', 'quezon city', 'quito',
  'rabat', 'raleigh', 'rawalpindi', 'recife', 'reims', 'rennes', 'reykjavik', 'richmond', 'riga', 'rijeka', 'rio de janeiro', 'riyadh', 'rochester', 'rome', 'rosario', 'rostov', 'rotterdam', 'rouen',
  'sacramento', 'salamanca', 'salem', 'salt lake city', 'salvador', 'salzburg', 'samara', 'samarkand', 'san antonio', 'san diego', 'san francisco', 'san jose', 'san juan', 'san salvador', 'sanaa', 'santander', 'santiago', 'santo domingo', 'sao paulo', 'sapporo', 'sarajevo', 'saskatoon', 'seattle', 'sendai', 'seoul', 'seville', 'shanghai', 'sheffield', 'shenyang', 'shenzhen', 'shiraz', 'siena', 'singapore', 'skopje', 'sochi', 'sofia', 'southampton', 'split', 'springfield', 'srinagar', 'st petersburg', 'stockholm', 'strasbourg', 'stuttgart', 'sucre', 'suez', 'surabaya', 'surat', 'suzhou', 'swansea', 'sydney',
  'tabriz', 'taipei', 'tallinn', 'tampa', 'tampere', 'tangier', 'tashkent', 'tbilisi', 'tegucigalpa', 'tehran', 'tel aviv', 'thessaloniki', 'tianjin', 'tijuana', 'timisoara', 'tirana', 'tokyo', 'toledo', 'toronto', 'toulouse', 'trabzon', 'trieste', 'tripoli', 'trondheim', 'tucson', 'tulsa', 'tunis', 'turin', 'turku',
  'ufa', 'ulaanbaatar', 'uppsala', 'utrecht',
  'valencia', 'valladolid', 'valletta', 'valparaiso', 'vancouver', 'varanasi', 'varna', 'venice', 'veracruz', 'verona', 'versailles', 'vienna', 'vigo', 'vilnius', 'vladivostok', 'volgograd',
  'warsaw', 'washington', 'wellington', 'wichita', 'winchester', 'windhoek', 'winnipeg', 'wroclaw', 'wuhan',
  'xiamen', 'xian', 'xining',
  'yangon', 'yaounde', 'yekaterinburg', 'yerevan', 'yogyakarta', 'yokohama', 'york',
  'zagreb', 'zanzibar', 'zaragoza', 'zurich',
];

const ANIMAL = [
  'aardvark', 'adder', 'albatross', 'alligator', 'alpaca', 'anaconda', 'anchovy', 'angelfish', 'ant', 'anteater', 'antelope', 'ape', 'aphid', 'armadillo', 'asp', 'axolotl',
  'baboon', 'badger', 'bandicoot', 'barnacle', 'barracuda', 'bass', 'bat', 'bear', 'beaver', 'bee', 'beetle', 'bison', 'blackbird', 'blowfish', 'bluebird', 'bluejay', 'boa', 'boar', 'bobcat', 'bonobo', 'bream', 'buffalo', 'bull', 'bulldog', 'bullfrog', 'bumblebee', 'butterfly', 'buzzard',
  'caiman', 'camel', 'canary', 'capybara', 'caracal', 'cardinal', 'caribou', 'carp', 'cassowary', 'cat', 'caterpillar', 'catfish', 'centipede', 'chameleon', 'cheetah', 'chickadee', 'chicken', 'chihuahua', 'chimpanzee', 'chinchilla', 'chipmunk', 'cicada', 'civet', 'clam', 'clownfish', 'cobra', 'cockatoo', 'cockroach', 'cod', 'condor', 'corgi', 'cormorant', 'cougar', 'cow', 'coyote', 'crab', 'crane', 'crayfish', 'cricket', 'crocodile', 'crow', 'cuckoo', 'curlew', 'cuttlefish',
  'dachshund', 'dalmatian', 'deer', 'dingo', 'dodo', 'dog', 'dolphin', 'donkey', 'dormouse', 'dove', 'dragonfly', 'dromedary', 'duck', 'dugong',
  'eagle', 'earthworm', 'earwig', 'echidna', 'eel', 'egret', 'eland', 'elephant', 'elk', 'emu', 'ermine',
  'falcon', 'ferret', 'finch', 'firefly', 'fish', 'flamingo', 'flea', 'flounder', 'fly', 'fox', 'frog',
  'gannet', 'gazelle', 'gecko', 'gerbil', 'gibbon', 'giraffe', 'gnat', 'gnu', 'goat', 'goldfinch', 'goldfish', 'goose', 'gopher', 'gorilla', 'grasshopper', 'greyhound', 'grizzly', 'groundhog', 'grouse', 'guinea pig', 'gull', 'guppy',
  'haddock', 'halibut', 'hamster', 'hare', 'hawk', 'hedgehog', 'hen', 'hermit crab', 'heron', 'herring', 'hippopotamus', 'hog', 'honeybee', 'hornbill', 'hornet', 'horse', 'hound', 'hummingbird', 'husky', 'hyena',
  'ibex', 'ibis', 'iguana', 'impala',
  'jackal', 'jackdaw', 'jackrabbit', 'jaguar', 'jay', 'jellyfish', 'jerboa',
  'kakapo', 'kangaroo', 'kea', 'kestrel', 'killer whale', 'kingfisher', 'kinkajou', 'kite', 'kiwi', 'koala', 'koi', 'komodo dragon', 'kookaburra', 'krill', 'kudu',
  'labrador', 'ladybug', 'lamb', 'lamprey', 'lark', 'leech', 'lemming', 'lemur', 'leopard', 'lion', 'lionfish', 'lizard', 'llama', 'lobster', 'locust', 'loon', 'loris', 'lovebird', 'lynx',
  'macaque', 'macaw', 'mackerel', 'magpie', 'mallard', 'mammoth', 'manatee', 'mandrill', 'manta ray', 'mantis', 'marlin', 'marmoset', 'marmot', 'marten', 'mastiff', 'mayfly', 'meerkat', 'millipede', 'mink', 'minnow', 'mockingbird', 'mole', 'mongoose', 'monkey', 'moose', 'moray eel', 'mosquito', 'moth', 'mouse', 'mule', 'muskox', 'muskrat', 'mussel',
  'narwhal', 'nautilus', 'newt', 'nightingale', 'numbat', 'nuthatch', 'nyala',
  'ocelot', 'octopus', 'okapi', 'opossum', 'orangutan', 'orca', 'oriole', 'oryx', 'osprey', 'ostrich', 'otter', 'owl', 'ox', 'oyster',
  'panda', 'pangolin', 'panther', 'parakeet', 'parrot', 'partridge', 'peacock', 'pelican', 'penguin', 'perch', 'petrel', 'pheasant', 'pig', 'pigeon', 'pika', 'pike', 'piranha', 'platypus', 'plover', 'polar bear', 'polecat', 'pomeranian', 'pony', 'poodle', 'porcupine', 'porpoise', 'possum', 'prawn', 'praying mantis', 'ptarmigan', 'pufferfish', 'puffin', 'pug', 'puma', 'python',
  'quail', 'quetzal', 'quokka', 'quoll',
  'rabbit', 'raccoon', 'ram', 'rat', 'rattlesnake', 'raven', 'ray', 'red panda', 'reindeer', 'rhea', 'rhinoceros', 'roadrunner', 'robin', 'rook', 'rooster', 'rottweiler',
  'sable', 'sailfish', 'salamander', 'salmon', 'sandpiper', 'sardine', 'scallop', 'scorpion', 'sea lion', 'sea otter', 'sea urchin', 'seagull', 'seahorse', 'seal', 'serval', 'shark', 'sheep', 'sheepdog', 'shoebill', 'shrew', 'shrimp', 'silkworm', 'silverfish', 'skink', 'skunk', 'skylark', 'sloth', 'slug', 'snail', 'snake', 'snapper', 'snow leopard', 'sole', 'spaniel', 'sparrow', 'spider', 'spider monkey', 'sponge', 'spoonbill', 'springbok', 'squid', 'squirrel', 'stag', 'starfish', 'starling', 'stick insect', 'stingray', 'stoat', 'stork', 'sturgeon', 'sunfish', 'swallow', 'swan', 'swift', 'swordfish',
  'tadpole', 'tamarin', 'tapir', 'tarantula', 'tarsier', 'tasmanian devil', 'termite', 'tern', 'terrier', 'tick', 'tiger', 'tilapia', 'toad', 'tortoise', 'toucan', 'tree frog', 'trout', 'tuatara', 'tuna', 'turkey', 'turtle',
  'uakari', 'urchin',
  'vampire bat', 'vicuna', 'viper', 'vole', 'vulture',
  'wallaby', 'walrus', 'warbler', 'warthog', 'wasp', 'water buffalo', 'weasel', 'weevil', 'whale', 'whippet', 'wildcat', 'wildebeest', 'wolf', 'wolverine', 'wombat', 'woodchuck', 'woodpecker', 'worm', 'wren',
  'x-ray fish', 'xerus', 'xray fish',
  'yak', 'yellowjacket',
  'zebra', 'zebrafish', 'zebu', 'zorilla',
];

const PLANT = [
  'acacia', 'agave', 'alder', 'alfalfa', 'almond', 'aloe', 'amaranth', 'amaryllis', 'anemone', 'anise', 'apple', 'apricot', 'arugula', 'ash', 'aspen', 'aster', 'avocado', 'azalea',
  'bamboo', 'banana', 'banyan', 'baobab', 'barley', 'basil', 'bay', 'bean', 'beech', 'beet', 'begonia', 'bellflower', 'bergamot', 'birch', 'blackberry', 'bluebell', 'blueberry', 'bougainvillea', 'boxwood', 'bracken', 'bramble', 'broccoli', 'buckwheat', 'bulrush', 'burdock', 'buttercup',
  'cabbage', 'cactus', 'calla lily', 'camellia', 'cantaloupe', 'caraway', 'cardamom', 'carnation', 'carrot', 'cassava', 'catnip', 'cattail', 'cauliflower', 'cedar', 'celery', 'chamomile', 'chard', 'cherry', 'chestnut', 'chickpea', 'chicory', 'chives', 'chrysanthemum', 'cilantro', 'clematis', 'clove', 'clover', 'coconut', 'columbine', 'coriander', 'corn', 'cornflower', 'cosmos', 'cotton', 'cottonwood', 'cranberry', 'cress', 'crocus', 'cucumber', 'cumin', 'currant', 'cyclamen', 'cypress',
  'daffodil', 'dahlia', 'daisy', 'dandelion', 'date palm', 'daylily', 'delphinium', 'dill', 'dogwood', 'duckweed', 'durian',
  'ebony', 'edelweiss', 'eggplant', 'elder', 'elderberry', 'elm', 'endive', 'eucalyptus',
  'fennel', 'fenugreek', 'fern', 'ficus', 'fig', 'fir', 'flax', 'forget-me-not', 'forsythia', 'foxglove', 'frangipani', 'freesia', 'fuchsia',
  'gardenia', 'garlic', 'gentian', 'geranium', 'gerbera', 'ginger', 'ginkgo', 'ginseng', 'gladiolus', 'goldenrod', 'gooseberry', 'gourd', 'grape', 'grapefruit', 'grass',
  'hawthorn', 'hazel', 'heather', 'hemlock', 'hemp', 'henna', 'hibiscus', 'hickory', 'holly', 'hollyhock', 'honeysuckle', 'hops', 'horseradish', 'hosta', 'hyacinth', 'hydrangea',
  'impatiens', 'indigo', 'iris', 'ivy',
  'jacaranda', 'jackfruit', 'jasmine', 'jonquil', 'juniper', 'jute',
  'kale', 'kelp', 'kiwi', 'kohlrabi', 'kudzu', 'kumquat',
  'larch', 'larkspur', 'laurel', 'lavender', 'leek', 'lemon', 'lemongrass', 'lentil', 'lettuce', 'lichen', 'lilac', 'lily', 'lime', 'linden', 'lotus', 'lupine',
  'magnolia', 'mahogany', 'mandrake', 'mango', 'maple', 'marigold', 'marjoram', 'milkweed', 'millet', 'mimosa', 'mint', 'mistletoe', 'monstera', 'morning glory', 'moss', 'mulberry', 'mushroom', 'mustard', 'myrtle',
  'narcissus', 'nasturtium', 'nectarine', 'nettle', 'nightshade', 'nutmeg',
  'oak', 'oat', 'okra', 'oleander', 'olive', 'onion', 'orange', 'orchid', 'oregano',
  'palm', 'pansy', 'papaya', 'papyrus', 'parsley', 'parsnip', 'passionflower', 'peach', 'pear', 'pecan', 'peony', 'pepper', 'peppermint', 'periwinkle', 'persimmon', 'petunia', 'philodendron', 'phlox', 'pine', 'pineapple', 'pistachio', 'pitcher plant', 'plantain', 'plum', 'poinsettia', 'pomegranate', 'poplar', 'poppy', 'potato', 'primrose', 'pumpkin',
  'quince', 'quinoa',
  'radish', 'ragweed', 'raspberry', 'rattan', 'redwood', 'reed', 'rhododendron', 'rhubarb', 'rice', 'rose', 'rosemary', 'rowan', 'rutabaga', 'rye',
  'saffron', 'sage', 'sagebrush', 'saguaro', 'sandalwood', 'scallion', 'sedge', 'sequoia', 'sesame', 'shallot', 'snapdragon', 'sorghum', 'sorrel', 'soybean', 'spearmint', 'spider plant', 'spinach', 'spruce', 'squash', 'strawberry', 'sugarcane', 'sumac', 'sunflower', 'sweet pea', 'sweet potato', 'sycamore',
  'tamarind', 'tangerine', 'tarragon', 'teak', 'thistle', 'thyme', 'tobacco', 'tomato', 'tulip', 'tumbleweed', 'turmeric', 'turnip',
  'ube', 'umbrella tree',
  'valerian', 'vanilla', 'venus flytrap', 'verbena', 'violet',
  'walnut', 'water lily', 'watercress', 'watermelon', 'wheat', 'willow', 'wintergreen', 'wisteria', 'witch hazel', 'wolfsbane',
  'xerophyte',
  'yam', 'yarrow', 'yew', 'ylang-ylang', 'yucca',
  'zinnia', 'zucchini',
];

const FOOD = [
  'almond', 'anchovy', 'apple', 'apricot', 'artichoke', 'arugula', 'asparagus', 'avocado',
  'bacon', 'bagel', 'baklava', 'banana', 'barley', 'basil', 'bean', 'beef', 'beet', 'beetroot', 'bell pepper', 'biryani', 'biscuit', 'blackberry', 'blueberry', 'bologna', 'borscht', 'bratwurst', 'bread', 'brie', 'brisket', 'broccoli', 'brownie', 'bruschetta', 'bulgur', 'bun', 'burger', 'burrito', 'butter', 'butterscotch',
  'cabbage', 'cake', 'calamari', 'calzone', 'candy', 'cannoli', 'cantaloupe', 'cappuccino', 'caramel', 'carrot', 'cashew', 'casserole', 'cauliflower', 'caviar', 'celery', 'cereal', 'ceviche', 'cheddar', 'cheese', 'cheeseburger', 'cheesecake', 'cherry', 'chicken', 'chickpea', 'chili', 'chips', 'chocolate', 'chorizo', 'chow mein', 'chowder', 'churro', 'chutney', 'ciabatta', 'cider', 'cinnamon', 'clam', 'cobbler', 'coconut', 'coffee', 'cola', 'coleslaw', 'cookie', 'corn', 'cornbread', 'couscous', 'crab', 'cracker', 'cream', 'crepe', 'croissant', 'croquette', 'cucumber', 'cupcake', 'curry', 'custard',
  'date', 'dill', 'donut', 'doughnut', 'dumpling',
  'eclair', 'edamame', 'egg', 'egg roll', 'eggnog', 'eggplant', 'empanada', 'enchilada', 'escargot', 'espresso',
  'fajita', 'falafel', 'feta', 'fettuccine', 'fig', 'fish', 'flan', 'flatbread', 'flour', 'focaccia', 'fondue', 'french fries', 'fries', 'frittata', 'fritter', 'fruitcake', 'fudge',
  'garlic', 'gazpacho', 'gelato', 'ginger', 'gnocchi', 'goulash', 'granola', 'grape', 'grapefruit', 'gravy', 'grits', 'guacamole', 'guava', 'gumbo', 'gyro',
  'halva', 'ham', 'hamburger', 'hazelnut', 'herring', 'honey', 'honeydew', 'horseradish', 'hotdog', 'hummus',
  'ice cream',
  'jackfruit', 'jalapeno', 'jam', 'jambalaya', 'jelly', 'jerky', 'juice',
  'kale', 'kebab', 'kefir', 'ketchup', 'kimchi', 'kiwi', 'kohlrabi', 'kombucha',
  'lamb', 'lasagna', 'latte', 'leek', 'lemon', 'lemonade', 'lentil', 'lettuce', 'lime', 'linguine', 'lobster', 'lollipop', 'lychee',
  'macaron', 'macaroni', 'mackerel', 'mandarin', 'mango', 'maple syrup', 'margarine', 'marmalade', 'marshmallow', 'marzipan', 'mayonnaise', 'meat', 'meatball', 'meatloaf', 'melon', 'meringue', 'milk', 'milkshake', 'mint', 'miso', 'mochi', 'mozzarella', 'muesli', 'muffin', 'mulberry', 'mushroom', 'mustard', 'mutton',
  'naan', 'nachos', 'nectarine', 'noodle', 'nougat', 'nut', 'nutmeg',
  'oat', 'oatmeal', 'octopus', 'okra', 'olive', 'omelet', 'omelette', 'onion', 'orange', 'oregano', 'oyster',
  'pad thai', 'paella', 'pancake', 'panini', 'papaya', 'paprika', 'parfait', 'parmesan', 'pasta', 'pastrami', 'pastry', 'pea', 'peach', 'peanut', 'peanut butter', 'pear', 'pecan', 'penne', 'pepper', 'pepperoni', 'persimmon', 'pesto', 'pho', 'pickle', 'pie', 'pilaf', 'pineapple', 'pistachio', 'pita', 'pizza', 'plantain', 'plum', 'polenta', 'pomegranate', 'popcorn', 'pork', 'porridge', 'potato', 'poutine', 'pretzel', 'prosciutto', 'prune', 'pudding', 'pumpkin',
  'quesadilla', 'quiche', 'quince', 'quinoa',
  'radish', 'raisin', 'ramen', 'raspberry', 'ravioli', 'relish', 'rhubarb', 'rice', 'ricotta', 'risotto', 'roast beef', 'rosemary', 'rye',
  'saffron', 'sage', 'salad', 'salami', 'salmon', 'salsa', 'salt', 'sandwich', 'sardine', 'sauce', 'sauerkraut', 'sausage', 'scallop', 'schnitzel', 'scone', 'seafood', 'seaweed', 'sesame', 'sherbet', 'shortbread', 'shrimp', 'sirloin', 'smoothie', 'soda', 'sorbet', 'souffle', 'soup', 'sourdough', 'soy sauce', 'spaghetti', 'spinach', 'spring roll', 'squash', 'squid', 'sriracha', 'steak', 'stew', 'strawberry', 'strudel', 'sugar', 'sundae', 'sushi', 'syrup',
  'tabbouleh', 'taco', 'taffy', 'tahini', 'tamale', 'tangerine', 'tapioca', 'taro', 'tart', 'tea', 'tempura', 'teriyaki', 'tiramisu', 'toast', 'toffee', 'tofu', 'tomato', 'tortellini', 'tortilla', 'truffle', 'tuna', 'turkey', 'turmeric', 'turnip', 'tzatziki',
  'udon',
  'vanilla', 'veal', 'venison', 'vermicelli', 'vinegar',
  'waffle', 'walnut', 'wasabi', 'watercress', 'watermelon', 'wheat', 'wine', 'wonton', 'wrap',
  'xylitol',
  'yam', 'yoghurt', 'yogurt',
  'ziti', 'zucchini',
];

const OBJECT = [
  'abacus', 'accordion', 'alarm clock', 'album', 'anchor', 'antenna', 'anvil', 'apron', 'armchair', 'ashtray', 'atlas', 'axe',
  'backpack', 'badge', 'bag', 'ball', 'balloon', 'banjo', 'barrel', 'basin', 'basket', 'basketball', 'bat', 'bathtub', 'baton', 'battery', 'beaker', 'bed', 'bell', 'belt', 'bench', 'bicycle', 'binoculars', 'birdcage', 'blackboard', 'blanket', 'blender', 'blinds', 'boat', 'bolt', 'book', 'bookcase', 'bookshelf', 'boot', 'bottle', 'bowl', 'box', 'bracelet', 'brick', 'briefcase', 'brooch', 'broom', 'brush', 'bucket', 'bulb', 'button',
  'cabinet', 'cable', 'cage', 'calculator', 'calendar', 'camera', 'candle', 'candlestick', 'cane', 'canoe', 'canteen', 'canvas', 'cap', 'car', 'card', 'carpet', 'cart', 'cassette', 'cauldron', 'cello', 'chain', 'chair', 'chalk', 'chandelier', 'chessboard', 'chest', 'chisel', 'clamp', 'clarinet', 'cleaver', 'clip', 'clipboard', 'cloak', 'clock', 'cloth', 'coat', 'coaster', 'coin', 'colander', 'comb', 'compass', 'computer', 'corkscrew', 'cot', 'couch', 'cradle', 'crate', 'crayon', 'crib', 'crowbar', 'crown', 'crutch', 'cufflink', 'cup', 'cupboard', 'curtain', 'cushion',
  'dagger', 'dartboard', 'darts', 'decanter', 'desk', 'dice', 'dictionary', 'dish', 'dishwasher', 'doll', 'domino', 'door', 'doorbell', 'doorknob', 'doormat', 'drawer', 'dresser', 'drill', 'drum', 'dryer', 'dumbbell', 'dustpan', 'duvet',
  'earphone', 'earring', 'easel', 'envelope', 'eraser',
  'fan', 'faucet', 'fence', 'figurine', 'file', 'fireplace', 'fishing rod', 'flag', 'flashlight', 'flask', 'flute', 'folder', 'football', 'footstool', 'fork', 'fountain pen', 'frame', 'freezer', 'fridge', 'frisbee', 'frying pan', 'funnel',
  'gavel', 'glass', 'glasses', 'globe', 'glove', 'glue', 'goblet', 'goggles', 'golf club', 'gong', 'grater', 'griddle', 'grill', 'guitar',
  'hacksaw', 'hairbrush', 'hairdryer', 'hammer', 'hammock', 'handbag', 'handcuffs', 'handkerchief', 'hanger', 'harmonica', 'harp', 'harpoon', 'hat', 'hatchet', 'headphone', 'heater', 'helmet', 'hinge', 'hoe', 'hook', 'hose', 'hourglass',
  'ink', 'inkwell', 'iron', 'ironing board',
  'jacket', 'jar', 'javelin', 'jeans', 'jigsaw', 'joystick', 'jug', 'jukebox', 'jump rope',
  'kayak', 'kettle', 'key', 'keyboard', 'keychain', 'kiln', 'kimono', 'kite', 'knapsack', 'knife', 'knob',
  'ladder', 'ladle', 'lamp', 'lampshade', 'lantern', 'laptop', 'lawnmower', 'leash', 'lens', 'lid', 'light', 'lighter', 'lipstick', 'lock', 'locket', 'loom', 'luggage', 'lute', 'lyre',
  'machete', 'magazine', 'magnet', 'mailbox', 'mandolin', 'map', 'marble', 'marker', 'mask', 'mat', 'matchbox', 'mattress', 'medal', 'megaphone', 'metronome', 'microphone', 'microscope', 'microwave', 'mirror', 'mitten', 'mixer', 'monocle', 'mop', 'mousetrap', 'mug',
  'nail', 'napkin', 'necklace', 'necktie', 'needle', 'net', 'notebook', 'nutcracker',
  'oar', 'oboe', 'organ', 'ornament', 'ottoman', 'oven', 'oven mitt',
  'pacifier', 'pad', 'paddle', 'padlock', 'paintbrush', 'pajamas', 'palette', 'pan', 'paper', 'parachute', 'parasol', 'peeler', 'pen', 'pencil', 'pendant', 'perfume', 'periscope', 'pestle', 'phone', 'piano', 'pickaxe', 'picture frame', 'piggy bank', 'pillow', 'pillowcase', 'pin', 'pipe', 'pitcher', 'pitchfork', 'plate', 'pliers', 'plunger', 'pocket', 'pogo stick', 'poncho', 'postcard', 'poster', 'pot', 'pouch', 'printer', 'projector', 'pulley', 'purse', 'puzzle',
  'quill', 'quilt', 'quiver',
  'racket', 'radio', 'raft', 'rake', 'rattle', 'razor', 'record player', 'refrigerator', 'remote control', 'ring', 'rocking chair', 'rolling pin', 'rope', 'rucksack', 'rug', 'ruler',
  'saddle', 'safe', 'sandal', 'sandpaper', 'satchel', 'saw', 'saxophone', 'scale', 'scarf', 'scissors', 'scooter', 'screen', 'screw', 'screwdriver', 'scroll', 'scythe', 'sewing machine', 'shears', 'shelf', 'shield', 'shoe', 'shoelace', 'shovel', 'shower', 'sieve', 'sink', 'skateboard', 'sketchbook', 'ski', 'skillet', 'sled', 'sledgehammer', 'sleeping bag', 'slingshot', 'slipper', 'snorkel', 'snowboard', 'soap', 'sock', 'sofa', 'spade', 'spatula', 'speaker', 'spear', 'sponge', 'spoon', 'spring', 'sprinkler', 'stamp', 'stapler', 'statue', 'stethoscope', 'stilts', 'stool', 'stopwatch', 'stove', 'stroller', 'suitcase', 'surfboard', 'sweater', 'sword', 'syringe',
  'table', 'tablet', 'tambourine', 'tape', 'tarp', 'teacup', 'teapot', 'teddy bear', 'telephone', 'telescope', 'tent', 'thermometer', 'thermos', 'thimble', 'thread', 'tie', 'timer', 'toaster', 'toolbox', 'toothbrush', 'torch', 'towel', 'toy', 'tray', 'tricycle', 'tripod', 'trombone', 'trophy', 'trowel', 'trumpet', 'trunk', 'tuba', 'tv', 'tweezers', 'typewriter',
  'ukulele', 'umbrella', 'unicycle', 'uniform', 'urn',
  'vacuum', 'vase', 'veil', 'vest', 'violin', 'visor', 'volleyball',
  'wagon', 'walkie talkie', 'wallet', 'wand', 'wardrobe', 'washing machine', 'wastebasket', 'watch', 'water bottle', 'watering can', 'wheel', 'wheelbarrow', 'wheelchair', 'whip', 'whisk', 'whistle', 'wig', 'window', 'wine glass', 'wire', 'wok', 'wrench', 'wristwatch',
  'x-ray', 'xylophone',
  'yacht', 'yardstick', 'yarn', 'yo-yo', 'yoke', 'yoyo',
  'zipper', 'zither',
];

const WORD_LISTS = {
  name: new Set(NAME),
  city: new Set(CITY),
  animal: new Set(ANIMAL),
  plant: new Set(PLANT),
  food: new Set(FOOD),
  object: new Set(OBJECT),
};

module.exports = { WORD_LISTS };
